# Generated by Django 4.2 on 2024-06-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reval_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100, null=True)),
                ('pn', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('qty', models.CharField(max_length=100, null=True)),
                ('usd', models.CharField(max_length=100, null=True)),
                ('scrap', models.FloatField(null=True)),
                ('unit_freight', models.FloatField(null=True)),
                ('ext_price', models.FloatField(null=True)),
                ('remark', models.CharField(max_length=100, null=True)),
                ('unit_price', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
