# Generated by Django 4.2 on 2024-06-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reval_file',
            name='quarter',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
